### ISSUE TITLE
Array not yet dim'd

### ISSUE THREAD

**Issue by sikosis** [AmiBlitz/AmiBlitz3#71]
`fmt$ = "%ld ($%lx)" + Chr$(10)`

Affected source: Chr$(10)

The above code fails to compile with that error about not being dim'd.

**Comment by honitos** [comment]
I can not reproduce this behaviour.
Is the function Chr$() tokenized, that means is it printed as bold ?
If not, the compiler did not recognize Chr$() as a function probably because not blitzlibs have been loaded.

Please open the instruction browser, all loaded libs will be displayed there.
Chr$() is part of the "stringfunclib".

**Comment by T0lk13n** [comment]
Cant test in the A1200 but under MorphOS it works correctly.

**Comment by mbergmann-sh** [comment]
This might happen if you forgot a closing bracket or use a call to function/statement with round brackets instead of curly brackets.
